### PR TITLE
[Revised #35] add GoogleAuthenticator#setCredentialRepository(..)

### PR DESCRIPTION
**Pull request by haochenx**

### CODE REVIEW

**Comment by ZKHelloworld** [comment]
I currently need this setCredentialRepository feature.
Hoping this pr will be merged soon.

**Comment by emcrisostomo** [comment]
The reason why I haven't merged this pull request is that I don't see the need of using an `AtomicReference`.  The author had submitted another #35 in the past and I argued about it, but the explanation I was given, literally: 

> so that one can distinguish whether the field is set to be null intentionally or just haven't been initialized

just didn't convince me.

`GoogleAuthenticator` is _not_ designed to be thread-safe: it's a lightweight object you can instantiate on a per-thread basis without worrying about performance (the only state it maintains is a random number generator that is reseeded periodically).  A trivial setter will suffice.

I will close this pull request for the same reason I've closed without merging #35 and will provide a setter myself as soon as I can.

**Comment by ZKHelloworld** [comment]
Alright then. A trivial setter would be great enrough. :)

**Comment by haochenx** [comment]
Okay, let's think this situation, if we have included a configuration file for the Java ServiceLoader API, and we want to disable the registered CredentialRepository, what can we do if we don't use a holder such as the AtomicReference that I'm using?

**Comment by haochenx** [comment]
Anyway, if you think the usage of AtomicReference is more confusing than the benefits it provides, then just strip its usage.

As I've already thrown away the project (which was a toy project) I used GoogleAuth, I cannot do it myself now.

**Comment by emcrisostomo** [comment]
Hi @haochenx, we could keep track of the setter invocation on a flag: I'm afraid thinking of an `Atomic*` class as a way to store "nullable references" is not clear at all.

**Comment by emcrisostomo** [comment]
Released in [1.0.0][release].

[release]: https://github.com/wstrange/GoogleAuth/releases/tag/1.0.0

**Comment by haochenx** [comment]
Haha, you're right. I actually wanted to use the Optional type, but thinking about compatibility before java 1.7, I just picked the most close class. I should have come up with the idea of utilising a separate field.

Thank you for the new release!

**Pull request closed without merging**
