### PR TITLE
fix typo, update unit testcases to junit4, simplify locking in ReseedingSecureRandom, fix findbugs warning

### PR DESCRIPTION
**Pull request by senthilkumar-kj**
With Junit4 we no longer need to extend TestCase.

### CODE REVIEW

**Comment by senthilkumar-kj** [comment]
Hi @emcrisostomo, you can find the findbugs report here - https://gist.github.com/senthilkumar-kj/4c9fe4112c1491a5bc04 (please download and view it in browser).

Regarding the locking in ReseedingSecureRandom, I think we do not need a read/write lock and can do the same job with just ReentrantLock. Please take a look. 

Thanks,

**Comment by emcrisostomo** [comment]
Hi @senthilkumar-kj,

Thank you very much.

I'm sorry I don't agree on using the `ReentrantLock`: the semantic of the two locks are very different.  It certainly "does the job", but it has two problems: it's not the same, and it's not required.

Why it's not the same: the existing implementation uses a read lock (lightweight and can be hold by more than one thread at a time) most of the time, and upgrade to a write lock when required. That class enables a GoogleAuthenticator instance to be used by more than one thread, and the read/write lock has been chosen because of the predictable (it's a counter with a fixed value, in fact) refresh pattern of the secure random instance.

Using a plain `ReentrantLock` is not even required in your implementation because the same thread doesn't ever try to reacquire a lock it owns.

As far as the three FindBugs warnings: the encoding one is cosmetic, since the BaseN codec output is predictable (its alphabet is known) and the String constructor from byte[] wouldn't produce different results. I'll fix it anyway. The byte one is going to be fixed as well.

Last but not least: in the future please try not to mix more than one thing in the same pull request.

**Comment by emcrisostomo** [comment]
Published v. [0.4.4] with those two fixes and pushed to OSSRH Maven repository.

[0.4.4]: https://github.com/wstrange/GoogleAuth/releases/tag/0.4.4

**Comment by senthilkumar-kj** [comment]
Thank you @emcrisostomo. 

I'll try to explain briefly regarding the lock and what I meant by it does the job. With my fix we acquire lock only when the count is over million. In other cases, we do not even acquire a lock. In the current implementation, every thread has to acquire a read lock. 

Plus, we do not start the try block as soon as we acquire the block as shown here in the example http://docs.oracle.com/javase/7/docs/api/java/util/concurrent/locks/ReentrantReadWriteLock.html. I believe this code does the exact same thing as the existing one. (Reported in FindBugs).

And sorry about that, will not mix more than one fix in a pull request next time.

**Comment by senthilkumar-kj** [comment]
Could you look at this - https://github.com/senthilkumar-kj/GoogleAuth/commit/231182133ff6e8b81ce161a9e4d3000c02377618 (I've made slight changes than the previous one). I believe this code and the existing one does the same job. Please correct me if I'm wrong.

**Comment by emcrisostomo** [comment]
Hi @senthilkumar-kj,

Thanks for your efforts and explanations.

In fact, I did not remember than some time ago I had loosened the count check: the current implementation does *not* enforce the creation of a new RNG at an *exact* number of counts, it just request that it be done as soon as a thread "realises" that it's time to do it.

As a consequence, I agree with you in removing the read lock.

**Comment by senthilkumar-kj** [comment]
Thank you @emcrisostomo. Can I send a pull request for this?

**Comment by emcrisostomo** [comment]
Hi @senthilkumar-kj,

Please, feel free to send any pull request: discussion usually promotes better deliverables.

In this case, though, please have a look at this [changeset]: since the read lock wasn't necessary, I'm just using plain synchronisation. IMHO, using a `ReentrantLock` adds more complexity than it's worth without gaining any of the niche benefits that kind of lock offers over this kind of synchronisation, in this specific use case. There's not going to be high contention, either, since at most a bunch of thread are asking for that lock every million requests or so.

[changeset]: https://github.com/wstrange/GoogleAuth/commit/d9b49d53bcf2106f9151f4e98d0d9cce88af09e4

**Comment by senthilkumar-kj** [comment]
Yes, that makes sense. Thanks for updating it. 😊

**Pull request closed without merging**
