### PR TITLE
HMAC Algorithm Expansion

### PR DESCRIPTION
**Pull request by jfonte-accesso**
This is a request to allow different HMAC algorithms to be used via the config builder.

The default HMAC algorithm remains SHA1, a new method is exposed on the config builder, and a test case against the RFC 6238 test vectors for SHA256 has been added.

Any feedback is appreciated. Thanks!

### CODE REVIEW

**Comment by wstrange** [comment]
This looks awesome John.

@emcrisostomo Has been tending the PRs for this project, so I'll defer to him.

**Comment by jfonte-accesso** [comment]
Thanks @wstrange!
Bumping the thread (@emcrisostomo)

**Comment by emcrisostomo** [comment]
Hi @jfonte-accesso, sorry for the belated answer, this sounds like a nice feature. I'll have a look at it very shortly.

**Comment by jfonte-accesso** [comment]
Bump :)

**Comment by wstrange** [comment]
@jfonte-accesso, I'll give @emcrisostomo another day to review, and then I will merge.

Thanks for your patience

**Comment by emcrisostomo** [comment]
Hi @jfonte-accesso,

Thanks for the contribution and sorry for the belated answer.

**Pull request merged**
