### PR TITLE
Add methods to take key and configuration outside of GoogleAuthentica…

### PR DESCRIPTION
**Pull request by jasonab**
…torKey. This allows for secrets saved in the database to regenerate their QR code.

### CODE REVIEW

**Comment by jasonab** [comment]
This is in regards to issue #60

**Comment by emcrisostomo** [comment]
Hi @jasonab,

Thank you very much for the pull request. However, I'm closing it because I decided to add a builder to let users create instances of the GoogleAuthenticatorKey class.

**Comment by jasonab** [comment]
No problem at all, thanks for making an active architecture decision on the project.

**Comment by emcrisostomo** [comment]
You're welcome. Also, I forgot to mention I updated the Texinfo documentation of the library.

**Pull request closed without merging**
